version: "3.9" 
services:
  parify-db: 
    image: postgres 
    restart: always 
    container_name: parify-db 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PDATA: /data/postgres 
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: